### ISSUE TITLE
Material files for simulation

### ISSUE THREAD

**Issue by leehoy** [DIDSR/VICTRE_MCGPU#1]
Hello,

I appreciate the nice code!

I'm trying to run MC simulation for DBT image generation using the breast phantom generated from the VICTRE project.

I found the necessary materials files in another repositories or archives, however, I'm not able to get carbonOxalate.mcgpu file for microcalcification.

I also tried to PENELOPE 2006 to generate material database and to create the material file. However, I can only get the latest version of PENELOPE, which is 2014, from my liaison officer who is in charge of distributing the software.

Is there any other repositories of ways to get the material files??

**Comment by YoelShoshan** [comment]
^ encountered the same problem, please describe how to find the material files, otherwise it's not possible to use the system.

Thanks :)

**Comment by andreubs** [comment]
Hi. I hope the code will work well in your simulations. I was waiting to finish the code documentation before adding all the auxiliary files, but it is true that this is taking too much time. I am happy to see interest in our work!

I have created a folder with a couple of example simulations, and the corresponding phantom and material files. Notice that the correspondence from phantom voxel number to material and density is, unfortunately, hard-coded in the code. So it is best to stick to the phantoms generated with Graff's software at this moment (I will try to improve this eventually).

Please, open more issues if you find more missing items, or if you have questions regarding the code execution (read carefully the comments in each line of the input file).

Best regards!
