### ISSUE TITLE
Source and detector modeling of a GE Pristina system

### ISSUE THREAD

**Issue by gmingjie** [DIDSR/VICTRE_MCGPU#2]
Hi, 

Thank you for sharing the code. 
I mainly work with GE Pristina systems, so I'm wondering if you have the source and detector modeling of a GE Pristina system? 

Thank you!

**Comment by andreubs** [comment]
Unfortunately our current software can only model Selenium direct-conversion detectors, or an ideal detector. Systems using a CsI scintillator can not be accurately modeled with the implemented detector model, but we hope to add this capability during this year. 

A possible, but less accurate,  way to simulate other detectors that might be reasonable in some applications that are not very sensitive to the detector model accuracy is the following. Set the input parameters of MCGPU to have an ideal detector (disable the fluorescence emission and electronic noise and set gain to 0 and Swank factor to 1); input the thickness and attenuation of the CsI layer (this will model well at least the geometric factors in the depth of interaction and transmission). Then after simulating these ‘ideal’ images, convolve them with the experimental CsI point spread function computed from MTF measurements (you can also simulate very high resolution images and re-bin them after the convolution to avoid artifacts in this process). The resulting images will miss some energy and depth-of-interaction effects, but might be usable with your application.

I hope this helps!
