### ISSUE TITLE
Would it be possible to share the configuration files for the other two types: dense and fatty?

### ISSUE THREAD

**Issue by shenghh2015** [DIDSR/VICTRE_MCGPU#3]
Thanks for your sharing the codes. Would it be possible to share the x-ray imaging configuration files for the other two types of phantoms, e.g. dense and fatty?

Thanks. Looking forward to your reply.

**Comment by andreubs** [comment]
Hi shenghh2015,

I am attaching below the 2 missing input files (but they are not really useful without the phantom files).

[input_fatty.txt](https://github.com/DIDSR/VICTRE_MCGPU/files/4269654/input_fatty.txt)
[input_dense.txt](https://github.com/DIDSR/VICTRE_MCGPU/files/4269651/input_dense.txt)

**Comment by shenghh2015** [comment]
Great, Thanks!

**Comment by shenghh2015** [comment]
Hi, could you please also share the energy spectrum files that correspond
to the imaging for dense and fatty? Thanks!

Best regards,
shenghh2015

**Comment by andreubs** [comment]
We used the same spectrum for fatty and scattered (30kVp) and for dense and hetero (28kVp), because each pair have similar thickness (files available at the folder example_simulations/spectrum). The spectra with the same filtration are very similar really with just a +-2 kVp.

**Comment by shenghh2015** [comment]
Thanks a lot for your feedback.
