### ISSUE TITLE
!!init_energy_spectrum ERROR!! Error trying to read the energy spectrum input file "W28kVp_Rh50um_Be1mm_SiemensBoone.spc".

### ISSUE THREAD

**Issue by supperpojke** [DIDSR/VICTRE_MCGPU#9]
!!init_energy_spectrum ERROR!! Error trying to read the energy spectrum input file "W28kVp_Rh50um_Be1mm_SiemensBoone.spc".

Hi,
Thank you for sharing the project. 
I am trying the example "MC-GPU_v1.5b_sample_mammo_and_DBT_simulation_InputDensity.in", and get the error information about the spectrum input file. Just checked the folder, there is not a file with this name. Could you help with it?
Best regards,
Pojke

**Comment by andreubs** [comment]
Hi Pojke,

The spectrum file you need is available in here (we shortened the name): 
https://github.com/DIDSR/VICTRE_MCGPU/blob/master/example_simulations/spectrum/W28kVp_Rh50um_Be1mm.spc

The input files in the example_simulations folder have the proper path for the spectrum and material files.

I hope the code works well now.

Andreu
